# Generated by Django 3.0.3 on 2020-03-19 10:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('staff_id', models.PositiveIntegerField(blank=True, max_length=20, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('units', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menu', models.ManyToManyField(to='restaurants.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('menu_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.MenuList')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('card_payment', 'card_payment'), ('pay_on_delivery', 'pay_on_delivery')], max_length=30)),
                ('status', models.CharField(choices=[('uncompleted', 'uncompleted'), ('pending', 'pending'), ('approved', 'approved'), ('canceled', 'canceled'), ('transit', 'transit'), ('completed', 'completed')], max_length=30)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.DeliveryCompany')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
    ]
