# Generated by Django 3.0.3 on 2020-03-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycompany',
            name='staff_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
