# Generated by Django 3.0.3 on 2020-03-25 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_order_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulist',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.MenuList'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.MenuList'),
        ),
    ]
